#!/bin/bash -el
# Authors: Seth McGinnis, Jacob Stuivenvolt-Allen
#
# clean_index.sh - Apply corrected CF metadata to a single climate index
# variable extracted from a (possibly multi-variable) GIS index output file.
#
# Part of the NA-CORDEX-CMIP6 post-processing workflow.  Called by
# commandfiles generated by index.py (cleanup.cmd).
#
# Reads cleanup specs from gis_cleanup.tsv and input variable metadata from
# gis_indexes.tsv (both in SETUPDIR).
#
#
# As needed: cleans up global metadata, extracts the relevant
# variable, fixes the time epoch, adds scalar threshold coordinate
# variable, renames variable, and adds correct attributes
#
# Usage: clean_index.sh INDEX INFILE OUTFILE SETUPDIR
#
#   INDEX    Index name (row key into gis_cleanup.tsv, e.g. CDD, CDDn)
#   INFILE   Raw index file produced by index.py's indices/merge steps
#   OUTFILE  Full path to cleaned output file
#   SETUPDIR Directory containing gis_cleanup.tsv and gis_indexes.tsv

set -eo pipefail

module load nco
module load cdo

padding="10000"  # 10 KB header padding reduces odds of file rewrites later

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

[[ $# -ne 4 ]] && {
    echo "Usage: $(basename "$0") INDEX INFILE OUTFILE SETUPDIR" >&2
    exit 1
}

index="$1"
infile="$2"
outfile="$3"
setupdir="$4"

# ---------------------------------------------------------------------------
# Load cleanup spec from SETUPDIR
# ---------------------------------------------------------------------------

cleanup_tsv="$setupdir/gis_cleanup.tsv"
indexes_tsv="$setupdir/gis_indexes.tsv"

[[ ! -f "$cleanup_tsv" ]] && {
    echo "Error: gis_cleanup.tsv not found: $cleanup_tsv" >&2
    exit 1
}
[[ ! -f "$indexes_tsv" ]] && {
    echo "Error: gis_indexes.tsv not found: $indexes_tsv" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# Look up the row for INDEX in gis_cleanup.tsv
# ---------------------------------------------------------------------------
# Columns: index, source_file, current_var_name, new_var_name, standard_name,
#          long_name, units, fix_time_epoch, threshold, longname_to_comment,
#          cell_methods, units_metadata

row="$(awk -F'\t' -v i="$index" 'NR>1 && $1==i {print; exit}' "$cleanup_tsv")"

[[ -z "$row" ]] && {
    echo "Error: Index '$index' not found in gis_cleanup.tsv" >&2
    exit 1
}

current_var_name=$(  echo "$row" | cut -f3)
new_var_name=$(      echo "$row" | cut -f4)
standard_name=$(     echo "$row" | cut -f5)
long_name=$(         echo "$row" | cut -f6)
units=$(             echo "$row" | cut -f7)
fix_time_epoch=$(    echo "$row" | cut -f8)
threshold=$(         echo "$row" | cut -f9)
longname_to_comment=$(echo "$row" | cut -f10)
cell_methods=$(      echo "$row" | cut -f11)
units_metadata=$(    echo "$row" | cut -f12)

# ---------------------------------------------------------------------------
# Look up input variable from gis_indexes.tsv (keyed on source_file).
# Used for threshold scalar coordinate metadata.
# ---------------------------------------------------------------------------

src_file="$(echo "$row" | cut -f2)"
idx_row="$(awk -F'\t' -v i="$src_file" 'NR>1 && $1==i {print; exit}' "$indexes_tsv")"

[[ -z "$idx_row" ]] && {
    echo "Error: source_file '$src_file' not found in gis_indexes.tsv" >&2
    exit 1
}

input_var="$(echo "$idx_row" | cut -f3 | cut -f1 -d+)"

# get attribute from input variable
get_attr() {
    local var="$1" attr="$2"
    ncdump -h "$infile" \
        | awk -v v="$var" -v a="$attr" \
              '$0 ~ "^\t\t"v":"a" " {
                  sub(/^[^"]*"/, ""); sub(/".*/, ""); print; exit
              }'
}

input_std_name=$(  get_attr "$current_var_name" "standard_name") || true
input_long_name=$( get_attr "$current_var_name" "long_name") || true
input_units=$(     get_attr "$current_var_name" "units") || true
input_cell_methods=$(get_attr "$current_var_name" "cell_methods") || true

# Threshold units: match input units, except K -> degC when input is Kelvin
thresh_units="$input_units"
[[ -n "$threshold" && "$input_units" == "K" ]] && thresh_units="degC"

mkdir -p "$(dirname "$outfile")"

# ---------------------------------------------------------------------------
# Step 1: Copy INFILE to OUTFILE, extracting only this variable.
# Keeps shared coordinate/grid variables (x, y, lat, lon, crs, time, bnds);
# ncks -v pulls those along automatically as coordinate/auxiliary variables.
# Pad header since we may add a scalar threshold coordinate later.
# ---------------------------------------------------------------------------

ncks -h -O -7 --hdr_pad $padding -v "$current_var_name" "$infile" "$outfile"

# ---------------------------------------------------------------------------
# Step 2: Delete stale tracking_id global attribute
# ---------------------------------------------------------------------------

ncatted -h -a tracking_id,global,d,, "$outfile"

# ---------------------------------------------------------------------------
# Step 3: Fix time epoch, if needed.  Rewrites time coordinate values and
# units in place to use the correct reference date (1950-01-01).
# ---------------------------------------------------------------------------

if [[ "$fix_time_epoch" == "TRUE" ]]; then
    cdo -O setreftime,1950-01-01,00:00:00,days "$outfile" "${outfile}.tmp"
    mv "${outfile}.tmp" "$outfile"
fi

# ---------------------------------------------------------------------------
# Step 4: Add threshold scalar coordinate, if applicable.
# Threshold metadata follows the *input* variable (standard_name, long_name,
# units, cell_methods), not the output index variable, since the threshold
# is a value in the same quantity space as the CDO operator's input.
# Units exception: K -> degC (threshold values in TSV are already in degC).
# ---------------------------------------------------------------------------

if [[ -n "$threshold" ]]; then
    ncap2 -h -A -s "threshold=double(${threshold})" "$outfile"
    ncatted -h \
        -a units,threshold,o,c,"${thresh_units}" \
        -a standard_name,threshold,o,c,"${input_std_name}" \
        -a long_name,threshold,o,c,"${input_long_name}" \
        "$outfile"
    [[ -n "$input_cell_methods" ]] && \
        ncatted -h -a cell_methods,threshold,o,c,"${input_cell_methods}" "$outfile"

    # Append "threshold" to the data variable's coordinates attribute
    ncatted -h -a coordinates,"${current_var_name}",a,c," threshold" "$outfile"
fi

# ---------------------------------------------------------------------------
# Step 5: Rename variable and write corrected attributes.
# ---------------------------------------------------------------------------

if [[ "$current_var_name" != "$new_var_name" ]]; then
    ncrename -h -v "${current_var_name},${new_var_name}" "$outfile"
fi

if [[ "$longname_to_comment" == "TRUE" ]]; then
    old_long_name="$(ncdump -h "$outfile" \
        | grep "${new_var_name}:long_name" \
        | sed 's/.*= "//; s/" *;.*//')"
    [[ -n "$old_long_name" ]] && \
        ncatted -h -a comment,"${new_var_name}",o,c,"${old_long_name}" "$outfile"
fi

ncatted -h \
    -a units,"${new_var_name}",o,c,"${units}" \
    -a standard_name,"${new_var_name}",o,c,"${standard_name}" \
    -a long_name,"${new_var_name}",o,c,"${long_name}" \
    "$outfile"

[[ -n "$cell_methods" && "$cell_methods" != \[TODO:* ]] && \
    ncatted -h -a cell_methods,"${new_var_name}",o,c,"${cell_methods}" "$outfile"

[[ -n "$units_metadata" ]] && \
    ncatted -h -a units_metadata,"${new_var_name}",o,c,"${units_metadata}" "$outfile"

echo "Done"
exit 0
