#!/bin/bash -el
# Authors: Seth McGinnis, Jacob Stuivenvolt-Allen
#
# clean_index.sh - Apply corrected CF metadata to a single climate index
# variable extracted from a (possibly multi-variable) GIS index output file.
#
# Part of the NA-CORDEX-CMIP6 post-processing workflow.  Called by
# commandfiles generated by index.py (cleanup.cmd).
#
# Reads cleanup specs from gis_cleanup.tsv (must be present in SETUPDIR,
# alongside this script).  One row == one call == one output file: when a
# source file contains more than one data variable (e.g. CDD and CDDn),
# each variable gets its own row, and clean_index.sh extracts just that
# variable (plus shared coordinates) out of INFILE into its own OUTFILE.
#
# Creates output by:
#   1. Copying INFILE to OUTFILE, extracting only the named variable
#      (drops the other data variable(s), if any, but keeps x/y/lat/lon/crs)
#   2. Fixing the time epoch, if needed (cdo)
#   3. Adding a threshold scalar coordinate, if needed (ncap2)
#   4. Renaming the variable and writing corrected attributes (ncatted)
#
# Usage: clean_index.sh INDEX INFILE OUTFILE SETUPDIR
#
#   INDEX    Row key into gis_cleanup.tsv (e.g. CDD, CDDn, TG10p)
#   INFILE   Raw index file produced by index.py's indices/merge steps
#   OUTFILE  Full path to cleaned output file
#   SETUPDIR Directory containing gis_cleanup.tsv
#
# Note: INDEX is the cleanup TSV key, not necessarily the same as the
# index.py "index" column when a source file splits into multiple rows
# (e.g. both CDD and CDDn rows share source_file CDD, but have distinct
# INDEX keys and distinct OUTFILEs).

set -euo pipefail

module load nco
module load cdo

padding="10000"  # 10 KB header padding reduces odds of file rewrites later

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

[[ $# -ne 4 ]] && {
    echo "Usage: $(basename "$0") INDEX INFILE OUTFILE SETUPDIR" >&2
    exit 1
}

index="$1"
infile="$2"
outfile="$3"
setupdir="$4"

# ---------------------------------------------------------------------------
# Load cleanup spec from SETUPDIR
# ---------------------------------------------------------------------------

cleanup_tsv="$setupdir/gis_cleanup.tsv"

[[ ! -f "$cleanup_tsv" ]] && {
    echo "Error: gis_cleanup.tsv not found: $cleanup_tsv" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# Look up the row for INDEX
# ---------------------------------------------------------------------------
# Columns: index, source_file, current_var_name, new_var_name, standard_name,
#          long_name, units, fix_time_epoch, threshold, longname_to_comment,
#          cell_methods, units_metadata

row="$(awk -F'\t' -v i="$index" 'NR>1 && $1==i {print; exit}' "$cleanup_tsv")"

[[ -z "$row" ]] && {
    echo "Error: Index '$index' not found in gis_cleanup.tsv" >&2
    exit 1
}

current_var_name=$(  echo "$row" | cut -f3)
new_var_name=$(       echo "$row" | cut -f4)
standard_name=$(      echo "$row" | cut -f5)
long_name=$(           echo "$row" | cut -f6)
units=$(               echo "$row" | cut -f7)
fix_time_epoch=$(      echo "$row" | cut -f8)
threshold=$(           echo "$row" | cut -f9)
longname_to_comment=$( echo "$row" | cut -f10)
cell_methods=$(        echo "$row" | cut -f11)
units_metadata=$(      echo "$row" | cut -f12)

mkdir -p "$(dirname "$outfile")"

# ---------------------------------------------------------------------------
# Step 1: Copy INFILE to OUTFILE, extracting only this variable.
# Keeps shared coordinate/grid variables (x, y, lat, lon, crs, time, bnds);
# ncks -v pulls those along automatically as coordinate/auxiliary variables.
# Pad header since we may add a scalar threshold coordinate later.
# ---------------------------------------------------------------------------

ncks -h -O -7 --hdr_pad $padding -v "$current_var_name" "$infile" "$outfile"

# ---------------------------------------------------------------------------
# Step 2: Fix time epoch, if needed.  Rewrites time coordinate values and
# units in place to use the correct reference date (1950-01-01).
# ---------------------------------------------------------------------------

if [[ "$fix_time_epoch" == "TRUE" ]]; then
    cdo -O setreftime,1950-01-01,00:00:00,days "$outfile" "${outfile}.tmp"
    mv "${outfile}.tmp" "$outfile"
fi

# ---------------------------------------------------------------------------
# Step 3: Add threshold scalar coordinate, if applicable.  Units match the
# main variable's (corrected) units.
# ---------------------------------------------------------------------------

if [[ -n "$threshold" ]]; then
    ncap2 -h -A -s "threshold=double(${threshold})" "$outfile"
    ncatted -h \
        -a units,threshold,o,c,"${units}" \
        -a long_name,threshold,o,c,"threshold value for ${new_var_name}" \
        "$outfile"
fi

# ---------------------------------------------------------------------------
# Step 4: Rename variable and write corrected attributes.
# Combining into as few ncatted invocations as possible reduces load on the
# Lustre metadata server when running in parallel across the full dataset.
# ---------------------------------------------------------------------------

if [[ "$current_var_name" != "$new_var_name" ]]; then
    ncrename -h -v "${current_var_name},${new_var_name}" "$outfile"
fi

# Preserve the existing (CDO-generated) long_name as `comment`, when it
# carries useful supplementary detail beyond the new short long_name.
if [[ "$longname_to_comment" == "TRUE" ]]; then
    old_long_name="$(ncks -M -m "$outfile" \
        | awk -v v="$new_var_name" \
              '$0 ~ "^"v" attribute [0-9]+: long_name"' \
        | sed -n 's/.*, value = //p')"
    [[ -n "$old_long_name" ]] && \
        ncatted -h -a comment,"${new_var_name}",o,c,"${old_long_name}" "$outfile"
fi

ncatted -h \
    -a units,"${new_var_name}",o,c,"${units}" \
    -a standard_name,"${new_var_name}",o,c,"${standard_name}" \
    -a long_name,"${new_var_name}",o,c,"${long_name}" \
    "$outfile"

[[ -n "$cell_methods" && "$cell_methods" != \[TODO:* ]] && \
    ncatted -h -a cell_methods,"${new_var_name}",o,c,"${cell_methods}" "$outfile"

[[ -n "$units_metadata" ]] && \
    ncatted -h -a units_metadata,"${new_var_name}",o,c,"${units_metadata}" "$outfile"

echo "Done"
exit 0
