#!/bin/bash -el
# Authors: Seth McGinnis, Jacob Stuivenvolt-Allen
#
# clean_index.sh - Apply corrected CF metadata to a single climate index
# output file (in place).
#
# Part of the postprocessing index-generation workflow.  Called by
# commandfiles generated by index.py (cleanup.cmd), on the files index.py's
# indices/derived steps wrote directly to OUTDIR.
#
# Reads index specs from gis_indexes.tsv (in SETUPDIR).  FILE is expected to
# contain exactly one data variable (whatever name CDO left it under); it
# gets renamed to the TSV's 'index' value and given corrected attributes.
# If the index has a threshold, a scalar threshold coordinate variable is
# added.
#
# Usage: clean_index.sh INDEX FILE SETUPDIR
#
#   INDEX    Index name (row key into gis_indexes.tsv, e.g. CDD, CDDn)
#   FILE     Raw index file to clean up in place
#   SETUPDIR Directory containing gis_indexes.tsv

set -eo pipefail

module load nco
module load cdo

padding="10000"  # 10 KB header padding reduces odds of file rewrites later

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

[[ $# -ne 3 ]] && {
    echo "Usage: $(basename "$0") INDEX FILE SETUPDIR" >&2
    exit 1
}

index="$1"
outfile="$2"
setupdir="$3"

# ---------------------------------------------------------------------------
# Load index spec from SETUPDIR
# ---------------------------------------------------------------------------

indexes_tsv="$setupdir/gis_indexes.tsv"

[[ ! -f "$indexes_tsv" ]] && {
    echo "Error: gis_indexes.tsv not found: $indexes_tsv" >&2
    exit 1
}

# ---------------------------------------------------------------------------
# Look up the row for INDEX in gis_indexes.tsv
# ---------------------------------------------------------------------------
# Columns: index, formula, threshold, th_units, out_units, input_vars,
#          long_name, description, standard_name, cell_methods,
#          units_metadata, _end

row="$(awk -F'\t' -v i="$index" 'NR>1 && $1==i {print; exit}' "$indexes_tsv")"

[[ -z "$row" ]] && {
    echo "Error: Index '$index' not found in gis_indexes.tsv" >&2
    exit 1
}

threshold=$(     echo "$row" | cut -f3)
th_units=$(      echo "$row" | cut -f4)
out_units=$(     echo "$row" | cut -f5)
long_name=$(     echo "$row" | cut -f7)
description=$(   echo "$row" | cut -f8)
standard_name=$( echo "$row" | cut -f9)
cell_methods=$(  echo "$row" | cut -f10)
units_metadata=$(echo "$row" | cut -f11)

# ---------------------------------------------------------------------------
# Discover the file's data variable name (expected: exactly one).
# ---------------------------------------------------------------------------

raw_var="$(cdo showname "$outfile" 2>/dev/null | xargs)"

[[ -z "$raw_var" ]] && {
    echo "Error: could not determine data variable name in $outfile" >&2
    exit 1
}
[[ "$raw_var" == *" "* ]] && {
    echo "Error: expected exactly one data variable in $outfile, got: $raw_var" >&2
    exit 1
}

# get attribute from the raw variable, before renaming
get_attr() {
    local attr="$1"
    ncdump -h "$outfile" \
        | awk -v v="$raw_var" -v a="$attr" \
              '$0 ~ "^\t\t"v":"a" " {
                  sub(/^[^"]*"/, ""); sub(/".*/, ""); print; exit
              }'
}

input_units=$(get_attr "units") || true

# Output units: carry through input's units unless out_units overrides it.
units="${out_units:-$input_units}"

# ---------------------------------------------------------------------------
# Step 1: Rewrite header in place, padded, since we may add a scalar
# threshold coordinate later.
# ---------------------------------------------------------------------------

ncks -h -O -7 --hdr_pad $padding "$outfile" "$outfile"

# ---------------------------------------------------------------------------
# Step 2: Delete stale tracking_id global attribute
# ---------------------------------------------------------------------------

ncatted -h -a tracking_id,global,d,, "$outfile"

# ---------------------------------------------------------------------------
# Step 3: Add threshold scalar coordinate, if applicable.  th_units is
# recorded explicitly in the TSV, so no unit-guessing is needed here.
# ---------------------------------------------------------------------------

if [[ -n "$threshold" ]]; then
    ncap2 -h -A -s "threshold=double(${threshold})" "$outfile"
    ncatted -h -a units,threshold,o,c,"${th_units}" "$outfile"

    # Append "threshold" to the data variable's coordinates attribute
    ncatted -h -a coordinates,"${raw_var}",a,c," threshold" "$outfile"
fi

# ---------------------------------------------------------------------------
# Step 4: Rename variable and write corrected attributes.
# ---------------------------------------------------------------------------

if [[ "$raw_var" != "$index" ]]; then
    ncrename -h -v "${raw_var},${index}" "$outfile"
fi

ncatted -h -a units,"${index}",o,c,"${units}" "$outfile"

[[ -n "$standard_name" ]] && \
    ncatted -h -a standard_name,"${index}",o,c,"${standard_name}" "$outfile"

[[ -n "$long_name" ]] && \
    ncatted -h -a long_name,"${index}",o,c,"${long_name}" "$outfile"

[[ -n "$description" ]] && \
    ncatted -h -a comment,"${index}",o,c,"${description}" "$outfile"

[[ -n "$cell_methods" && "$cell_methods" != \[TODO:* ]] && \
    ncatted -h -a cell_methods,"${index}",o,c,"${cell_methods}" "$outfile"

[[ -n "$units_metadata" ]] && \
    ncatted -h -a units_metadata,"${index}",o,c,"${units_metadata}" "$outfile"

echo "Done"
exit 0
