#!/bin/bash -el
# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis
#
# cmorize.sh - Apply CF-compliant metadata and WCRP-CORDEX archiving
# attributes to an extracted WRF variable file.
#
# Part of the NA-CORDEX-CMIP6 post-processing workflow.  Called by
# commandfiles generated by format.sh.
#
# Reads simulation metadata from sim.env and per-variable specs from
# var_table.tsv, both of which must be present in the same directory as
# this script (copied there by launch_multi from the format/data directory).
#
# Creates output by:
#   1. Trimming sponge zone from spatial coordinates in wrf.xy.coords.nc
#   2. Appending the (trimmed) data variable from INFILE
#   3. Writing all CF and CORDEX global and variable attributes
#
# Usage: cmorize.sh VAR FREQ INFILE OUTFILE SETUPDIR
#
#   VAR      CMORized variable name (e.g. tas, pr, sftlf)
#   FREQ     Output frequency (1hr, 6hr, day, fx).
#   INFILE   Input file from extract step
#   OUTFILE  Full path to output file
#   SETUPDIR Directory containing sim.env, var_table.tsv, wrf.xy.coords.nc
#            (the SETUPDIR from setup.py)
#
# Note: FREQ is needed as an argument because the freq column in
# var_table is the requested frequency, which may differ from actual.

set -euo pipefail

module load nco
module load cdo

padding="10000"  # 10 KB header padding reduces odds of file rewrites later

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

[[ $# -ne 5 ]] && {
    echo "Usage: $(basename "$0") VAR FREQ INFILE OUTFILE SETUPDIR" >&2
    exit 1
}

var="$1"
freq="$2"
infile="$3"
outfile="$4"
setupdir="$5"

# ---------------------------------------------------------------------------
# Load simulation metadata from SETUPDIR
# ---------------------------------------------------------------------------

sim_env="$setupdir/sim.env"
var_table="$setupdir/var_table.tsv"
coord_file="$setupdir/wrf.xy.coords.nc"

[[ ! -f "$sim_env" ]] && {
    echo "Error: sim.env not found: $sim_env" >&2
    echo "Run setup.py and pass its output directory as SETUPDIR." >&2
    exit 1
}
[[ ! -f "$var_table" ]] && {
    echo "Error: var_table.tsv not found: $var_table" >&2
    exit 1
}
[[ ! -f "$coord_file" ]] && {
    echo "Error: wrf.xy.coords.nc not found: $coord_file" >&2
    echo "Run setup.py before cmorize.sh." >&2
    exit 1
}

# Source simulation metadata as shell variables
source "$sim_env"

# ---------------------------------------------------------------------------
# Look up per-variable specs from var_table.tsv
# ---------------------------------------------------------------------------
# Columns: var, freq, units, cell_methods, positive, levels, refh, plev,
#          quant, standard_name, long_name
#
# Note: freq (column 2) is CORDEX-requested frequency and is ignored,
# because actual frequency may differ based on what was saved.

var_row="$(awk -F'\t' -v v="$var" 'NR>1 && $1==v {print; exit}' "$var_table")"

[[ -z "$var_row" ]] && {
    echo "Error: Variable '$var' not found in var_table.tsv" >&2
    exit 1
}

units=$(        echo "$var_row" | cut -f3)
cell_methods=$( echo "$var_row" | cut -f4)
positive=$(     echo "$var_row" | cut -f5)
levels=$(       echo "$var_row" | cut -f6)
refh=$(         echo "$var_row" | cut -f7)
plev=$(         echo "$var_row" | cut -f8)
quant=$(        echo "$var_row" | cut -f9)
standard_name=$(echo "$var_row" | cut -f10)
long_name=$(    echo "$var_row" | cut -f11)

# ---------------------------------------------------------------------------
# Derived metadata
# ---------------------------------------------------------------------------

tracking_id="hdl:21.14103/$(uuidgen)"

# Sponge zone trim indices derived from sponge_cells (set in sim_config.yml,
# sourced via sim.env).  NCO uses 0-based indices; the upper bound is negative
# to trim from the end regardless of domain size.
x_trim="${sponge_cells},-$((sponge_cells + 1))"
y_trim="${sponge_cells},-$((sponge_cells + 1))"

# ---------------------------------------------------------------------------
# write_attributes OUTFILE COORDS
#
# Write all CF and CORDEX global and variable attributes to OUTFILE.
# COORDS is the value for the variable's coordinates attribute
# (e.g. "lat lon" or "lat lon height").
#
# Called after all data and coordinate variables have been appended.
# Combining all ncatted calls into as few invocations as possible reduces
# load on the Lustre metadata server when running in parallel across the
# full dataset.
# ---------------------------------------------------------------------------

write_attributes() {
    local outfile="$1"
    local coords="$2"

    # Clear existing global and data-variable attributes first
    ncatted -h -a ,"$var",d,, -a ,global,d,, "$outfile"

    ncatted -h \
        -a Conventions,global,o,c,"CF-1.11" \
        -a activity_id,global,o,c,"${activity_id}" \
        -a contact,global,o,c,"${contact}" \
        -a creation_date,global,o,c,"${creation_date}" \
        -a domain,global,o,c,"${domain}" \
        -a domain_id,global,o,c,"${domain_id}" \
        -a driving_experiment,global,o,c,"${driving_experiment}" \
        -a driving_experiment_id,global,o,c,"${driving_experiment_id}" \
        -a driving_institution_id,global,o,c,"${driving_institution_id}" \
        -a driving_source_id,global,o,c,"${driving_source_id}" \
        -a driving_variant_label,global,o,c,"${driving_variant_label}" \
        -a frequency,global,o,c,"${freq}" \
        -a grid,global,o,c,"${grid}" \
        -a institution,global,o,c,"${institution}" \
        -a institution_id,global,o,c,"${institution_id}" \
        -a license,global,o,c,"${license}" \
        -a mip_era,global,o,c,"${mip_era}" \
        -a product,global,o,c,"${product}" \
        -a project_id,global,o,c,"${project_id}" \
        -a references,global,o,c,"${references}" \
        -a source,global,o,c,"${source}" \
        -a source_id,global,o,c,"${source_id}" \
        -a source_type,global,o,c,"${source_type}" \
        -a tracking_id,global,o,c,"${tracking_id}" \
        -a variable_id,global,o,c,"${var}" \
        -a version_realization,global,o,c,"${version_realization}" \
        "$outfile"

    ncatted -h \
        -a units,"${var}",o,c,"${units}" \
        -a standard_name,"${var}",o,c,"${standard_name}" \
        -a long_name,"${var}",o,c,"${long_name}" \
        -a coordinates,"${var}",o,c,"${coords}" \
        -a grid_mapping,"${var}",o,c,"crs" \
        -a _FillValue,"${var}",o,f,1.e20 \
        -a missing_value,"${var}",o,f,1.e20 \
        "$outfile"

    # Optional attributes: only written when present
    [[ -n "$positive" && "$positive" != "--" ]] && \
        ncatted -h -a positive,"${var}",o,c,"${positive}" "$outfile"

    [[ "$cell_methods" != "None" && -n "$cell_methods" ]] && \
        ncatted -h -a cell_methods,"${var}",o,c,"${cell_methods}" "$outfile"
}

# ---------------------------------------------------------------------------
# Fixed-level (fx) variables -- no time dimension
# ---------------------------------------------------------------------------

if [[ "$levels" == "fixed" ]]; then

    mkdir -p "$(dirname "$outfile")"

    # Extract coordinates trimmed to interior domain, then append data variable.
    ncks -h -O -7 --hdr_pad $padding -d x,$x_trim -d y,$y_trim \
	 "$coord_file" "$outfile"
    ncks -h -A -d x,$x_trim -d y,$y_trim -v "$var" "$infile" "$outfile"

    write_attributes "$outfile" "lat lon"

    echo "Done"
    exit 0
fi

# ---------------------------------------------------------------------------
# Single-level variables
#
# Time coordinate (including bounds for extensive variables) is written
# correctly by postprocess.machinery.py, so no CDO reformatting is needed.
# We start directly from the trimmed coord file and append the data variable.
# ---------------------------------------------------------------------------

mkdir -p "$(dirname "$outfile")"


# Step 1: Copy spatial coordinates trimmed to interior domain & pad header
ncks -h -O -7 --hdr_pad $padding -d x,$x_trim -d y,$y_trim \
     "$coord_file" "$outfile"

# Add vertical scalar coordinate if appropriate (mutually exclusive options)
#   levels=pressure : create plev scalar coord (Pa) from the plev column
#   refh set        : create height scalar coord (m) above ground
#   neither         : surface variable, coords are just "lat lon"

if [[ "$levels" == "pressure" ]]; then
    [[ -z "$plev" || "$plev" == "--" ]] && {
        echo "Error: levels=pressure but no plev value in var_table.tsv for $var" >&2
        exit 1
    }
    ncap2 -h -A -s "plev=double(${plev})" "$outfile"
    ncatted -h \
        -a units,plev,o,c,Pa \
        -a long_name,plev,o,c,pressure \
        -a standard_name,plev,o,c,air_pressure \
        -a positive,plev,o,c,down \
        -a axis,plev,o,c,Z \
        "$outfile"
    coords="lat lon plev"

elif [[ -n "$refh" && "$refh" != "--" ]]; then
    ncap2 -h -A -s "height=double(${refh})" "$outfile"
    ncatted -h \
        -a units,height,o,c,m \
        -a long_name,height,o,c,height \
        -a standard_name,height,o,c,height \
        -a positive,height,o,c,up \
        -a axis,height,o,c,Z \
        "$outfile"
    coords="lat lon height"
else
    coords="lat lon"
fi

# Step 2: Append data variable with sponge zone trimmed.
# Chunking (--chunk_map rd1) is important for downstream CDO/NCO performance.
ncks -h -A --mk_rec_dmn time --chunk_map rd1 \
     -d x,$x_trim -d y,$y_trim -v "$var" \
    "$infile" "$outfile"

# Step 3: Write all CF and CORDEX attributes
write_attributes "$outfile" "$coords"

echo "Done"
exit 0
