#!/bin/bash -el
# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis
#
# cmorize.sh - Apply CF-compliant metadata and WCRP-CORDEX archiving
# attributes to an extracted WRF variable file.
#
# Part of the NA-CORDEX-CMIP6 post-processing workflow.  Called by
# commandfiles generated by format.sh.
#
# Reads simulation metadata from sim.env and per-variable specs from
# var_table.tsv, both of which must be present in the same directory as
# this script (copied there by launch_multi from the format/data directory).
#
# Creates output by:
#   1. Extracting and reformatting the time coordinate
#   2. Setting the reference epoch
#   3. Adding time_bnds and ajusting time coordinates based on cell_methods
#   4. Appending spatial coordinates from wrf.xy.coords.nc
#   5. Trimming the sponge zone and appending the data variable
#   6. Writing all CF and CORDEX global and variable attributes
#
# Usage: cmorize.sh VAR INFILE OUTFILE SETUPDIR
#
#   VAR      CMORized variable name (e.g. tas, pr, sftlf)
#   INFILE   Input file from extract step
#   OUTFILE  Full path to output file
#   SETUPDIR Directory containing sim.env, var_table.tsv, wrf.xy.coords.nc
#            (the SETUPDIR from setup.py)

set -euo pipefail

module load nco
module load cdo

# ---------------------------------------------------------------------------
# Arguments
# ---------------------------------------------------------------------------

[[ $# -ne 4 ]] && {
    echo "Usage: $(basename "$0") VAR INFILE OUTFILE SETUPDIR" >&2
    exit 1
}

var="$1"
infile="$2"
outfile="$3"
setupdir="$4"

# ---------------------------------------------------------------------------
# Load simulation metadata from SETUPDIR
# ---------------------------------------------------------------------------

sim_env="$setupdir/sim.env"
var_table="$setupdir/var_table.tsv"
coord_file="$setupdir/wrf.xy.coords.nc"

[[ ! -f "$sim_env" ]] && {
    echo "Error: sim.env not found: $sim_env" >&2
    echo "Run setup.py and pass its output directory as SETUPDIR." >&2
    exit 1
}
[[ ! -f "$var_table" ]] && {
    echo "Error: var_table.tsv not found: $var_table" >&2
    exit 1
}
[[ ! -f "$coord_file" ]] && {
    echo "Error: wrf.xy.coords.nc not found: $coord_file" >&2
    echo "Run setup.py before cmorize.sh." >&2
    exit 1
}

# Source simulation metadata as shell variables
source "$sim_env"

# ---------------------------------------------------------------------------
# Look up per-variable specs from var_table.tsv
# ---------------------------------------------------------------------------
# Columns: var, freq, units, cell_methods, positive, levels, refh, plev,
#          quant, standard_name, long_name

var_row="$(awk -F'\t' -v v="$var" 'NR>1 && $1==v {print; exit}' "$var_table")"

[[ -z "$var_row" ]] && {
    echo "Error: Variable '$var' not found in var_table.tsv" >&2
    exit 1
}

freq=$(         echo "$var_row" | cut -f2)
units=$(        echo "$var_row" | cut -f3)
cell_methods=$( echo "$var_row" | cut -f4)
positive=$(     echo "$var_row" | cut -f5)
levels=$(       echo "$var_row" | cut -f6)
refh=$(         echo "$var_row" | cut -f7)
plev=$(         echo "$var_row" | cut -f8)
quant=$(        echo "$var_row" | cut -f9)
standard_name=$(echo "$var_row" | cut -f10)
long_name=$(    echo "$var_row" | cut -f11)

# ---------------------------------------------------------------------------
# Derived metadata
# ---------------------------------------------------------------------------

tracking_id="hdl:21.14103/$(uuidgen)"

# Sponge zone trim indices derived from sponge_cells (set in sim_config.yml,
# sourced via sim.env).  NCO uses 0-based indices; the upper bound is negative
# to trim from the end regardless of domain size.
x_trim="${sponge_cells},-$((sponge_cells + 1))"
y_trim="${sponge_cells},-$((sponge_cells + 1))"

# Interval length in days for each output frequency.  Note: this gets
# used in an ncap2 call, so express it precisely here and let ncap2
# handle calculating it to avoid errors due to loss of precision.
case "$freq" in
    1hr) interval="(1/24.0)" ;;
    6hr) interval="(6/24.0)" ;;
    day) interval="1" ;;
    *)   interval="" ;;
esac

# ---------------------------------------------------------------------------
# write_attributes OUTFILE COORDS
#
# Write all CF and CORDEX global and variable attributes to OUTFILE.
# COORDS is the value for the variable's coordinates attribute
# (e.g. "lat lon" or "lat lon height").
#
# Called after all data and coordinate variables have been appended.
# Combining all ncatted calls into as few invocations as possible reduces
# load on the Lustre metadata server when running in parallel across the
# full dataset.
# ---------------------------------------------------------------------------

write_attributes() {
    local outfile="$1"
    local coords="$2"

    # Clear existing global and variable-level attributes first
    ncatted -h -a ,"$var",d,, -a ,global,d,, "$outfile"

    ncatted -h \
        -a Conventions,global,o,c,"CF-1.11" \
        -a activity_id,global,o,c,"${activity_id}" \
        -a contact,global,o,c,"${contact}" \
        -a creation_date,global,o,c,"${creation_date}" \
        -a domain,global,o,c,"${domain}" \
        -a domain_id,global,o,c,"${domain_id}" \
        -a driving_experiment,global,o,c,"${driving_experiment}" \
        -a driving_experiment_id,global,o,c,"${driving_experiment_id}" \
        -a driving_institution_id,global,o,c,"${driving_institution_id}" \
        -a driving_source_id,global,o,c,"${driving_source_id}" \
        -a driving_variant_label,global,o,c,"${driving_variant_label}" \
        -a frequency,global,o,c,"${freq}" \
        -a grid,global,o,c,"${grid}" \
        -a institution,global,o,c,"${institution}" \
        -a institution_id,global,o,c,"${institution_id}" \
        -a license,global,o,c,"${license}" \
        -a mip_era,global,o,c,"${mip_era}" \
        -a product,global,o,c,"${product}" \
        -a project_id,global,o,c,"${project_id}" \
        -a references,global,o,c,"${references}" \
        -a source,global,o,c,"${source}" \
        -a source_id,global,o,c,"${source_id}" \
        -a source_type,global,o,c,"${source_type}" \
        -a tracking_id,global,o,c,"${tracking_id}" \
        -a variable_id,global,o,c,"${var}" \
        -a version_realization,global,o,c,"${version_realization}" \
        "$outfile"

    ncatted -h \
        -a units,"${var}",o,c,"${units}" \
        -a standard_name,"${var}",o,c,"${standard_name}" \
        -a long_name,"${var}",o,c,"${long_name}" \
        -a coordinates,"${var}",o,c,"${coords}" \
        -a grid_mapping,"${var}",o,c,"crs" \
        -a _FillValue,"${var}",o,f,1.e20 \
        -a missing_value,"${var}",o,f,1.e20 \
        "$outfile"

    # Optional attributes: only written when present
    [[ -n "$positive" && "$positive" != "--" ]] && \
        ncatted -h -a positive,"${var}",o,c,"${positive}" "$outfile"

    [[ "$cell_methods" != "None" && -n "$cell_methods" ]] && \
        ncatted -h -a cell_methods,"${var}",o,c,"${cell_methods}" "$outfile"
}

# ---------------------------------------------------------------------------
# Fixed-level (fx) variables -- no time dimension
# ---------------------------------------------------------------------------

if [[ "$levels" == "fixed" ]]; then

    mkdir -p "$(dirname "$outfile")"

    # Extract coordinates trimmed to interior domain, then append data variable
    ncks -h -d x,$x_trim -d y,$y_trim "$coord_file" "$outfile"
    ncks -h -A -d x,$x_trim -d y,$y_trim -v "$var" "$infile" "$outfile"

    write_attributes "$outfile" "lat lon"

    echo "Done"
    exit 0
fi

# ---------------------------------------------------------------------------
# Single-level variables
#
# This approach is a bit roundabout to avoid rewriting the entire file
# multiple times, which is very slow.  The CDO setreftime command
# (which is the best option for this operation) requires separate
# input and output files, so we process the time coordinate first,
# using a tempfile.  Then we can add in coordinates, followed by data.
# ---------------------------------------------------------------------------

mkdir -p "$(dirname "$outfile")"

padding="10000"  # 10 KB header padding reduces odds of file rewrites later
tempfile="${outfile}.cmortemp.nc"

# Step 1: Extract time coordinate into a temporary file.
# CDO will drop time if there's no data variable, so create a dummy one.
ncks -h -O --hdr_pad $padding -v time "$infile" "$tempfile"
ncatted -h -a history,global,d,, "$tempfile"
ncap2 -h -A -s 'dummy[$time]=0.0f' "$tempfile" "$tempfile"
ncap2 -h -O -s 'time=double(time)' "$tempfile" "$tempfile"

# Time attributes must be set before setreftime
ncatted -h \
	-a long_name,time,o,c,time \
	-a standard_name,time,o,c,time \
	-a axis,time,o,c,T \
	"$tempfile"


# Step 2: Set epoch & calendar and remove dummy variable. Calendar
# (inherited from driver) is defined in sim_config.yml, $calendar is
# set by sourcing sim.env.

epoch="1950-01-01 00:00:00"  ## required by CORDEX spec

cdo --no_history -setreftime,"${epoch/ /,/},1day" -setcalendar,"${calendar}" \
    "$tempfile" "$outfile"
ncatted -h \
    -a units,time,o,c,"days since ${epoch}" \
    -a calendar,time,o,c,"${calendar}" \
    "$outfile"
ncks -h -O -7 --no_alphabetize -x -v dummy "$outfile" "$outfile"


# Step 3: Adjust time coordinate and add time_bnds
# time-intensive (instantaneous) vars: time at beginning of interval
# time-extensive (interval-stat) vars: time at midpoint of interval

# Note: CF doesn't require time_bnds for instantaneous vars, but
# providing it helps CDO get things right when aggregating later on

ncap2 -h -A -s "defdim(\"bnds\",2); \
      	       time_bnds[\$time,\$bnds]=0.0; \
    	       time_bnds(:,0)=time; \
    	       time_bnds(:,1)=time+${interval}; \
      	       time@bounds=\"time_bnds\";" \
      "$outfile" "$outfile"

time_extensive='time: (mean|min|max)'
if [[ "$cell_methods" =~ $time_extensive ]]; then
    # shift time coordinate to the midpoint of the interval
    ncap2 -h -O -s "time+=${interval}/2.0" "$outfile" "$outfile"
fi


# Step 4: Append spatial coordinates (trimmed to interior domain, excluding
# the sponge zone).  Variable ordering is also established here.
#
# Vertical scalar coordinate (mutually exclusive options):
#   levels=pressure : create plev scalar coord (Pa) from the plev column
#   refh set        : create height scalar coord (m) above ground
#   neither         : surface variable, coords are just "lat lon"
ncks -h -A -d x,$x_trim -d y,$y_trim "$coord_file" "$outfile"

if [[ "$levels" == "pressure" ]]; then
    [[ -z "$plev" || "$plev" == "--" ]] && {
        echo "Error: levels=pressure but no plev value in var_table.tsv for $var" >&2
        exit 1
    }
    ncap2 -h -A -s "plev=double(${plev})" "$outfile"
    ncatted -h \
        -a units,plev,o,c,Pa \
        -a long_name,plev,o,c,pressure \
        -a standard_name,plev,o,c,air_pressure \
        -a positive,plev,o,c,down \
        -a axis,plev,o,c,Z \
        "$outfile"
    coords="lat lon plev"

elif [[ -n "$refh" && "$refh" != "--" ]]; then
    ncap2 -h -A -s "height=double(${refh})" "$outfile"
    ncatted -h \
        -a units,height,o,c,m \
        -a long_name,height,o,c,height \
        -a standard_name,height,o,c,height \
        -a positive,height,o,c,up \
        -a axis,height,o,c,Z \
        "$outfile"
    coords="lat lon height"
else
    coords="lat lon"
fi

rm "$tempfile"

# Step 5: Append data variable with sponge zone trimmed.
# Chunking (--chunk_map rd1) is important for downstream CDO/NCO performance.
ncks -h -A -C --chunk_map rd1 -d x,$x_trim -d y,$y_trim -v "$var" \
    "$infile" "$outfile"

# Step 6: Write all CF and CORDEX attributes
write_attributes "$outfile" "$coords"

echo "Done"
exit 0
