name: nac6
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.14.4
    - cartopy=0.25.0
    - cftime=1.6.5
    - matplotlib=3.10.9
    - numpy=2.4.3
    - pandas=3.0.2
    - pyyaml=6.0.3
    - ruff=0.15.11
    - xarray=2026.4.0
    - cmip7-repack
    - pip=26.0.1
    - datamash=1.9
    - pip:
        - thermofeel==2.1.7
        - esgf-qa
        - esgvoc
