# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis

# Purpose:
# --------
# Entry point for NA-CORDEX-CMIP6 variable extraction.  Handles argument
# parsing, simulation metadata, file loading, output writing, and dispatch.
# Extract functions for individual variables live in postprocess.variables.py,
# which is imported after shared state is set up so the functions can close
# over names defined here.
#
# Variable metadata specifications are taken from:
# https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables

# USAGE NOTES:
# -----

# 1. This script processes a single year of data for one variable,
#    specified via commandline arguments.

# argument 1 : Path to sim.env (generated by setup.py)
# argument 2 : Path to wrfoutput files (chunk directory)
# argument 3 : Year (int)
# argument 4 : Variable (CMORized var name)
# argument 5 : Output directory (where variable subdirs are created)

# 2. It creates variable subdirectories under OUTDIR (argument 5) and
#    writes post-processed output there.  It does not change the
#    working directory; all paths are handled explicitly.

# 3. It is designed for command-file parallelism via launch_cf on
#    Casper HPC at NCAR.  It requires both NCO and CDO; when running
#    in parallel, they need to be made available via `module load`
#    commands in config_env.sh

# 4. 12-km WRF output is very large; be sure to request sufficient memory
#    (~100GB)

# 5. wbgt, utci, and humidex require the thermofeel package (ECMWF).
#    The provided nac6 conda environment includes it; create and activate
#    it from the repo with:
#      conda env create -f postprocess/environment.yml
#      conda activate nac6

# Example execution:
# ------------------------------------------------
# $ python postprocess.machinery.py {sim_env} {wrfout_path} 1980 tas {outdir}
# ------------------------------------------------

import thermofeel
from collections import defaultdict
import xarray as xr
from xarray import ufuncs
import numpy as np
import glob
import sys
import os
import time
import resource
import warnings

t0 = time.perf_counter()

# -----------------
# keyword arguments

sim_env     = sys.argv[1]  # path to sim.env
wrfout_path = sys.argv[2]  # path to wrf output
year        = sys.argv[3]  # year
variable    = sys.argv[4]  # variable (cmorized syntax)
outdir      = sys.argv[5]  # output directory (variable subdirs created here)

os.makedirs(outdir, exist_ok=True)

# -------------------------------
# START OF USER DEFINED VARIABLES
# -------------------------------

# Setting to True will overwrite all post-processed data: careful!
do_overwrite_existing = True

# filename prefixes for the different types of wrfout files
wrfout_fx_fname   = "wrfout_5day_d01_"  # files that contain fixed vars
wrfout_hour_fname = "wrfout_hour_d01_"  # hourly outputs
wrfout_6hr_fname  = "wrfout_d01_"       # 6-hourly outputs
wrfout_afwa_fname = "wrfout_afwa_d01_"  # AFWA diagnostics
wrfout_pres_fname = "wrfout_pres_d01_"  # pressure-level outputs
wrfout_zlev_fname = "wrfout_zlev_d01_"  # height-AGL outputs

# -------------------------------
# END OF USER DEFINED VARIABLES
# -------------------------------


# sim.env loading
# ---------------
# Reads simulation metadata from a shell key=value file generated by setup.py.
# Values are stripped of surrounding quotes (added by setup.py for values
# containing spaces).  This replaces the hardcoded _cal, wrfinput_path, and
# fname_base components that previously lived in the USER DEFINED VARIABLES
# section.

def load_sim_env(path):
    """Parse a shell key=value file into a dict, stripping surrounding quotes."""
    cfg = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    return cfg

_cfg = load_sim_env(sim_env)

# Simulation-specific settings read from sim.env
_cal          = _cfg['calendar']
wrfinput_path = _cfg['wrfinput_path']

# fname_base components
_dom = _cfg['domain_id']              # e.g. NAM-12
_drs = _cfg['driving_source_id']      # e.g. ERA5
_dre = _cfg['driving_experiment_id']  # e.g. evaluation
_drv = _cfg['driving_variant_label']  # e.g. r1i1p1f1
_org = _cfg['institution_id']         # e.g. NCAR
_src = _cfg['source_id']              # e.g. WRF461S-SN
_ver = _cfg['version_realization']    # e.g. v1-r1

# Base filename string (without leading var and trailing freq/timespan)
# See CORDEX-CMIP6 archiving specifications for file naming conventions.
fname_base = f'{_dom}_{_drs}_{_dre}_{_drv}_{_org}_{_src}_{_ver}'


# Dimension renaming (specified by CORDEX)
dname_map_t   = {'Time': 'time'}
dname_map_xy  = {'west_east': 'x', 'south_north': 'y'}
dname_map_xyt = dname_map_t | dname_map_xy

# 'rd1' chunking pattern (applied before dimension renaming)
_CHUNKS = {'Time': 1, 'south_north': 337, 'west_east': 354}


# File naming
# -----------
def make_fname(var, cmor_freq):
    """Construct the output filename for a variable at a given frequency."""
    if cmor_freq == '1hr':
        return f'{var}_{fname_base}_1hr_{year}010100-{year}123123.nc'
    elif cmor_freq == '6hr':
        return f'{var}_{fname_base}_6hr_{year}010100-{year}123118.nc'
    elif cmor_freq == 'day':
        return f'{var}_{fname_base}_day_{year}0101-{year}1231.nc'
    elif cmor_freq == 'mon':
        return f'{var}_{fname_base}_mon_{year}01-{year}12.nc'


# Time coordinate construction
# ----------------------------

# Calendar (_cal) is read from sim.env above.

# Note that although accumulated variables have an extra timestep
# going into the extract_* functions, after differencing they are the
# correct length, so they don't need a different time coordinate.

def _build_time_dim(yr, freq_hours):
    """CFTimeIndex at freq_hours intervals for yr."""
    return xr.date_range(start=f'{yr}-01-01',
                         end=f'{int(yr)+1}-01-01',
                         freq=f'{freq_hours}h',
                         inclusive='left',
                         unit='s',
                         calendar=_cal,
                         use_cftime=True,
                         )


# File loading
# ------------
# load_wrf is called at the dispatch site using parameters from _LOADER.
# The day-before file is prepended for accumulated variables so that the
# first diff gives the correct first-interval value.
#
# _day_before_file assumes Dec 31 exists in the prior year (which it
# does in standard and no-leap calendars as represented by WRF).

def _day_before_file(prefix, yr):
    """Return list containing the Dec 31 file of the prior year for prefix."""
    matches = sorted(glob.glob(f'{wrfout_path}/{prefix}{int(yr)-1}-12-31*'))
    if not matches:
        raise FileNotFoundError(
            f'Day-before file not found for year {yr} '
            f'(pattern: {wrfout_path}/{prefix}{int(yr)-1}-12-31*)')
    return matches

def load_wrf(prefix, yr, accumulated=False):
    """Load WRF output files for the given year into a dataset.

    Globs for files matching prefix+yr, sorts lexically, and prepends
    the last timestep of the day-before file when accumulated=True.
    Renames WRF dimensions to CORDEX conventions."""
    files = sorted(glob.glob(f'{wrfout_path}/{prefix}{yr}-*'))
    if not files:
        raise FileNotFoundError(
            f'No WRF files found for year {yr} '
            f'(pattern: {wrfout_path}/{prefix}{yr}-*)')

    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', message='.*separate the stored chunks.*')
        ds = xr.open_mfdataset(files,
                               concat_dim='Time',
                               combine='nested',
                               chunks=_CHUNKS,
                               mask_and_scale=False,
                               decode_times=False,
                               decode_coords=False,
                               ).fillna(1.e20)

        if accumulated:
            prev_file = _day_before_file(prefix, yr)
            prev_ds = xr.open_mfdataset(prev_file,
                                        concat_dim='Time',
                                        combine='nested',
                                        chunks=_CHUNKS,
                                        mask_and_scale=False,
                                        decode_times=False,
                                        decode_coords=False,
                                        ).isel(Time=[-1]).fillna(1.e20)
            # NB: list index [-1] prevents loss of time dim, which
            # leads to unwanted dimension reordering on concatenation
            ds = xr.concat([prev_ds, ds], dim='Time')

    return ds.rename(dname_map_xyt)


# fx dataset: loaded once at startup since multiple extract functions use it
fx_glob = f'{wrfout_path}/{wrfout_fx_fname}{year}*'
if not (fx_matches := glob.glob(fx_glob)):
    raise FileNotFoundError(f'No fx files found matching: {fx_glob}')
ds_fx = xr.open_dataset(fx_matches[0])


# Output existence check
# ----------------------
def _output_needed(var, fout):
    if os.path.exists(os.path.join(outdir, var, fout)) and not do_overwrite_existing:
        print(f'{var}/{fout} EXISTS : Skipping')
        return False
    return True


# Write extracted variables
# -------------------------
# Writes raw extracted data to outdir/var/fname.nc.
def write_vars(var_da_list):
    for var, cmor_freq, da in var_da_list:
        fout = make_fname(var, cmor_freq)
        if not _output_needed(var, fout):
            continue

        vardir = os.path.join(outdir, var)
        os.makedirs(vardir, exist_ok=True)
        outpath = os.path.join(vardir, fout)

        da.astype(np.float32).to_netcdf(outpath)


# Import extract functions
# ------------------------
# All shared state above is now defined; importing variables.py here allows
# its functions to close over names in this module's global namespace.
_variables_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                               'postprocess.variables.py')
with open(_variables_path) as _f:
    exec(compile(_f.read(), _variables_path, 'exec'), globals())


# Dispatch table
# --------------
# _EXTRACT maps variable names to their extract function.
# _LOADER maps variable names to (prefix, freq_hours, accumulated).
# _OUTFREQ maps variable names to their output frequency.
#
# At the call site, load_wrf and _build_time_dim are called using _LOADER
# parameters, then ds and time_dim are passed into extract_fn.
#
# wbgt and utci both resolve to the combined extract_wbgt_utci function and
# are called directly as special cases (no ds or time_dim).  Submitting
# utci as a standalone job would conflict with wbgt output; use --vars wbgt
# to get both.

_EXTRACT = {var: globals()[f'extract_{var}']
            for var in ['clt', 'evspsbl', 'hurs', 'huss', 'pr', 'ps',
                        'psl', 'rlds', 'rsds', 'sfcWind', 'tas',
                        'tasmax', 'tasmin', 'uas', 'vas',
                        'snw', 'snd', 'mrso', 'mrros', 'mrro',
                        'rsus', 'rlus', 'hfls', 'hfss', 'snm',
                        'ua700', 'ua500', 'ua250',
                        'va700', 'va500', 'va250',
                        'ta700', 'ta500', 'ta250',
                        'zg700', 'zg500', 'zg250',
                        'hus700', 'hus500', 'hus250',
                        'ua50m', 'ua100m', 'ua150m',
                        'va50m', 'va100m', 'va150m',
                        'cape', 'cin', 'prw', 'fzra',
                        'heatidx', 'wchill', 'humidex',
                        ]}

_EXTRACT['wbgt'] = extract_wbgt_utci
_EXTRACT['utci'] = extract_wbgt_utci

_OUTFREQ = defaultdict(lambda: '1hr',
                       tasmax='day', tasmin='day',
                       snw='6hr', snd='6hr', mrso='6hr', mrros='6hr',
                       mrro='6hr', rsus='6hr', rlus='6hr', hfls='6hr',
                       hfss='6hr', snm='6hr',
                       ua700='6hr', ua500='6hr', ua250='6hr',
                       va700='6hr', va500='6hr', va250='6hr',
                       ta700='6hr', ta500='6hr', ta250='6hr',
                       zg700='6hr', zg500='6hr', zg250='6hr',
                       hus700='6hr', hus500='6hr', hus250='6hr',
                       ua50m='6hr', ua100m='6hr', ua150m='6hr',
                       va50m='6hr', va100m='6hr', va150m='6hr',
                       )

# (prefix, freq_hours, accumulated)
_LOADER = defaultdict(lambda: (wrfout_hour_fname, 1, False), {
    'pr'     : (wrfout_hour_fname,  1, True),
    'rsds'   : (wrfout_hour_fname,  1, True),
    'rlds'   : (wrfout_hour_fname,  1, True),
    'psl'    : (wrfout_afwa_fname,  1, False),
    'mrro'   : (wrfout_6hr_fname,   6, True),
    'mrros'  : (wrfout_6hr_fname,   6, True),
    'snm'    : (wrfout_6hr_fname,   6, True),
    'snw'    : (wrfout_6hr_fname,   6, False),
    'snd'    : (wrfout_6hr_fname,   6, False),
    'mrso'   : (wrfout_6hr_fname,   6, False),
    'rsus'   : (wrfout_6hr_fname,   6, False),
    'rlus'   : (wrfout_6hr_fname,   6, False),
    'hfls'   : (wrfout_6hr_fname,   6, False),
    'hfss'   : (wrfout_6hr_fname,   6, False),
    'ua700'  : (wrfout_pres_fname,  6, False),
    'ua500'  : (wrfout_pres_fname,  6, False),
    'ua250'  : (wrfout_pres_fname,  6, False),
    'va700'  : (wrfout_pres_fname,  6, False),
    'va500'  : (wrfout_pres_fname,  6, False),
    'va250'  : (wrfout_pres_fname,  6, False),
    'ta700'  : (wrfout_pres_fname,  6, False),
    'ta500'  : (wrfout_pres_fname,  6, False),
    'ta250'  : (wrfout_pres_fname,  6, False),
    'zg700'  : (wrfout_pres_fname,  6, False),
    'zg500'  : (wrfout_pres_fname,  6, False),
    'zg250'  : (wrfout_pres_fname,  6, False),
    'hus700' : (wrfout_pres_fname,  6, False),
    'hus500' : (wrfout_pres_fname,  6, False),
    'hus250' : (wrfout_pres_fname,  6, False),
    'ua50m'  : (wrfout_zlev_fname,  6, False),
    'ua100m' : (wrfout_zlev_fname,  6, False),
    'ua150m' : (wrfout_zlev_fname,  6, False),
    'va50m'  : (wrfout_zlev_fname,  6, False),
    'va100m' : (wrfout_zlev_fname,  6, False),
    'va150m' : (wrfout_zlev_fname,  6, False),
    'cape'   : (wrfout_afwa_fname,  1, False),
    'cin'    : (wrfout_afwa_fname,  1, False),
    'prw'    : (wrfout_afwa_fname,  1, False),
    'fzra'   : (wrfout_afwa_fname,  1, True),
    'heatidx': (wrfout_afwa_fname,  1, False),
    'wchill' : (wrfout_afwa_fname,  1, False),
    'humidex': (wrfout_hour_fname,  1, False),
})

# Special-case variables that load their own files one at a time
_SELF_LOADING = {'wbgt', 'utci'}


# Call functions
# --------------
extract_fn = _EXTRACT.get(variable)
if extract_fn is None:
    print(f'Warning: unknown variable {variable}')
else:
    if _output_needed(variable, make_fname(variable, _OUTFREQ[variable])):
        if variable in _SELF_LOADING:
            write_vars(extract_fn())
        else:
            prefix, freq_hours, accumulated = _LOADER[variable]
            ds       = load_wrf(prefix, year, accumulated)
            time_dim = _build_time_dim(year, freq_hours)
            write_vars(extract_fn(ds, time_dim))
            ds.close()

print(f'postproc time: {time.perf_counter() - t0:.1f} sec')
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f'postproc max memory: {mem / (1024*1024):.1f} GB')
