# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis

# Purpose:
# --------
# Extract WBGT and UTCI from a single day's WRF hourly output file.
# Both indices are computed together since they share the expensive
# MRT calculation.
#
# This is a standalone script; it does not import postprocess.machinery.py
# or postprocess.variables.py.  Shared physics (_vapor_pressure_from_q)
# is duplicated here intentionally; consolidate if the two diverge.
#
# USAGE:
#   python postprocess.wbgt.py SETUPDIR INFILE OUTDIR
#
#   SETUPDIR  Directory containing sim.env (produced by setup.py)
#   INFILE    Single WRF hourly file: wrfout_hour_d01_YYYY-MM-DD_HH:MM:SS
#   OUTDIR    Output directory (wbgt.1hr/ and utci.1hr/ created here)
#
# Output files:
#   OUTDIR/wbgt.1hr/wbgt_{fname_base}_1hr_{YYYYMMDD}0000-{YYYYMMDD}2300.nc
#   OUTDIR/utci.1hr/utci_{fname_base}_1hr_{YYYYMMDD}0000-{YYYYMMDD}2300.nc
#
# References:
#   MRT: Di Napoli et al. (2020), Int J Biometeorol, 64:1233-1245
#   Globe T: Guo et al. (2018), Energy and Buildings
#   Wet bulb T: Stull (2011), J Appl Meteorol Climatol, 50:2267-2269
#   WBGT: ISO 7243 (2017); WBGT = 0.7*Tw + 0.2*Tg + 0.1*Ta
#   thermofeel: Brimicombe et al. (2022), SoftwareX, 18, 101005

import thermofeel
import xarray as xr
import numpy as np
import pandas as pd
import sys
import os
import re
import time
import resource

t0 = time.perf_counter()

# -----------------
# Arguments

setupdir = sys.argv[1]
infile   = sys.argv[2]
outdir   = sys.argv[3]

os.makedirs(outdir, exist_ok=True)

# -----------------
# sim.env loading
# Reads simulation metadata from a shell key=value file generated by setup.py.
# Values are stripped of surrounding quotes (added by setup.py for values
# containing spaces).

def load_sim_env(path):
    """Parse a shell key=value file into a dict, stripping surrounding quotes."""
    cfg = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    cfg['time_units'] = f"days since {cfg['epoch']}"
    return cfg

_cfg = load_sim_env(os.path.join(setupdir, 'sim.env'))

_dom = _cfg['domain_id']
_drs = _cfg['driving_source_id']
_dre = _cfg['driving_experiment_id']
_drv = _cfg['driving_variant_label']
_org = _cfg['institution_id']
_src = _cfg['source_id']
_ver = _cfg['version_realization']

fname_base = f'{_dom}_{_drs}_{_dre}_{_drv}_{_org}_{_src}_{_ver}'

# -----------------
# Parse date from filename
# Expected format: wrfout_hour_d01_YYYY-MM-DD_HH:MM:SS

_fname = os.path.basename(infile)
_m = re.search(r'(\d{4})-(\d{2})-(\d{2})_(\d{2})', _fname)
if not _m:
    print(f'Error: could not parse date from filename: {_fname}', file=sys.stderr)
    sys.exit(1)

year, mon, day = _m.group(1), _m.group(2), _m.group(3)
date_str  = f'{year}{mon}{day}'   # YYYYMMDD, used in output filenames

# -----------------
# Time coordinate
# WBGT/UTCI are time: point (instantaneous), so no time_bnds.

_t_encoding = {
    'units':    _cfg['time_units'],
    'calendar': _cfg['calendar'],
    'dtype':    np.float64,
}

time_da = xr.DataArray(
    xr.date_range(
        start=f'{year}-{mon}-{day}',
        periods=24,
        freq='1h',
        calendar=_cfg['calendar'],
        use_cftime=True,
        unit='s',
    ),
    dims=['time'],
    attrs={
        'long_name':     'time',
        'standard_name': 'time',
        'axis':          'T',
    },
)
time_da.encoding = _t_encoding

# -----------------
# Output filenames

wbgt_fout = os.path.join(
    outdir, 'wbgt.1hr',
    f'wbgt_{fname_base}_1hr_{date_str}0000-{date_str}2300.nc')
utci_fout = os.path.join(
    outdir, 'utci.1hr',
    f'utci_{fname_base}_1hr_{date_str}0000-{date_str}2300.nc')

os.makedirs(os.path.join(outdir, 'wbgt.1hr'), exist_ok=True)
os.makedirs(os.path.join(outdir, 'utci.1hr'), exist_ok=True)

# -----------------
# WRF variables needed

_WBGT_WRF_VARS = ['T2', 'Q2', 'PSFC', 'U10', 'V10', 'COSZEN',
                   'SWDOWN', 'SWDDNI', 'GLW', 'LWUPB', 'ALBEDO']

# -----------------
# Physics helpers

def _vapor_pressure_from_q(q, P):
    """Vapor pressure (Pa) from mixing ratio (kg/kg) and pressure (Pa)."""
    hus = q / (1 + q)    # mixing ratio -> specific humidity
    eps = 0.62197
    return hus * P / (eps + hus * (1.0 - eps))


def _compute_wbgt_utci_arrays(ds):
    """Compute WBGT and UTCI from a single-day WRF dataset.

    Returns (wbgt, utci) as float32 arrays shaped (time, y, x).
    MRT is computed once and shared between both indices to avoid
    redundant radiation processing.
    """
    coszen = np.clip(ds['COSZEN'].values, 0.0, 1.0)
    SWDOWN = np.maximum(np.nan_to_num(ds['SWDOWN'].values, nan=0.0), 0.0)
    SWDDNI = np.maximum(np.nan_to_num(ds['SWDDNI'].values, nan=0.0), 0.0)
    GLW    = np.maximum(np.nan_to_num(ds['GLW'].values,    nan=0.0), 0.0)
    LWUPB  = np.maximum(np.nan_to_num(ds['LWUPB'].values,  nan=0.0), 0.0)
    ALBEDO = np.nan_to_num(ds['ALBEDO'].values, nan=0.2)
    T2   = ds['T2'].values
    Q2   = ds['Q2'].values
    PSFC = ds['PSFC'].values
    U10  = ds['U10'].values
    V10  = ds['V10'].values

    ssrd = SWDOWN
    fdir = np.minimum(SWDDNI * coszen, ssrd)
    ssr  = SWDOWN * (1.0 - ALBEDO)
    strd = GLW
    strr = GLW - LWUPB

    mrt = thermofeel.calculate_mean_radiant_temperature(
        ssrd=ssrd, ssr=ssr, dsrp=SWDDNI,
        strd=strd, fdir=fdir, strr=strr,
        cossza=coszen,
    )

    wspd  = np.maximum(np.sqrt(U10**2 + V10**2), 0.5)
    Q2_safe = np.maximum(Q2, 0.0)
    e_a   = _vapor_pressure_from_q(Q2_safe, PSFC)
    e_hPa = np.maximum(e_a / 100.0, 0.001)
    ln_e  = np.log(e_hPa / 6.1078)
    tdew  = (237.3 * ln_e) / (17.27 - ln_e) + 273.15   # dew point (K)

    wbgt = thermofeel.calculate_wbgt(t2_k=T2, mrt=mrt, va=wspd, td_k=tdew)
    utci = thermofeel.calculate_utci(t2_k=T2, va=wspd, mrt=mrt, td_k=tdew)

    # Mask UTCI outside the valid input range of the thermofeel polynomial
    ta_c  = T2 - 273.15
    mrt_c = mrt - 273.15
    valid = (
        (ta_c  >= -50) & (ta_c  <= 50) &
        (wspd  <= 17) &
        ((mrt_c - ta_c) >= -30) & ((mrt_c - ta_c) <= 70)
    )
    utci = np.where(valid, utci, np.nan)

    return wbgt.astype(np.float32), utci.astype(np.float32)


# -----------------
# Load, compute, write

_chunks = {'Time': 1, 'south_north': 337, 'west_east': 354}

ds = xr.open_dataset(infile, engine='netcdf4',
                     chunks=_chunks,
                     mask_and_scale=False,
                     decode_times=False,
                     decode_coords=False)[_WBGT_WRF_VARS]
ds = ds.rename({'Time': 'time', 'west_east': 'x', 'south_north': 'y'})

wbgt_arr, utci_arr = _compute_wbgt_utci_arrays(ds)
ds.close()

_encoding_base = {
    'time': _t_encoding,
}

xr.DataArray(wbgt_arr, dims=['time', 'y', 'x'], coords={'time': time_da}) \
  .to_dataset(name='wbgt') \
  .to_netcdf(wbgt_fout,
             encoding={'wbgt': {'_FillValue': np.float32(1.e20)},
                       **_encoding_base},
             unlimited_dims=['time'])

xr.DataArray(utci_arr, dims=['time', 'y', 'x'], coords={'time': time_da}) \
  .to_dataset(name='utci') \
  .to_netcdf(utci_fout,
             encoding={'utci': {'_FillValue': np.float32(1.e20)},
                       **_encoding_base},
             unlimited_dims=['time'])

print(f'  wbgt/utci: {date_str} finished')
print(f'postproc time: {time.perf_counter() - t0:.1f} sec')
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f'postproc max memory: {mem / (1024*1024):.1f} GB')
