# Authors: Seth McGinnis, Jacob Stuivenvolt-Allen

# Purpose:
# --------
# Entry point for NA-CORDEX-CMIP6 variable extraction.  Handles argument
# parsing, simulation metadata, file loading, output writing, and dispatch.
# Extract functions for individual variables live in postproc_vars.py,
# which is imported after shared state is set up so the functions can close
# over names defined here.
#
# Variable metadata specifications are taken from:
# https://github.com/WCRP-CORDEX/cordex-cmip6-cmor-tables

# USAGE NOTES:
# -----

# 1. This script processes a single year of data for one variable,
#    specified via commandline arguments.

# argument 1 : Setup directory (contains sim.env and var_table.tsv,
#              generated by setup.py)
# argument 2 : Path to wrfoutput files (chunk directory)
# argument 3 : Year (int)
# argument 4 : Variable (CMORized var name)
# argument 5 : Output directory (where variable subdirs are created)

# 2. It creates variable subdirectories under OUTDIR (argument 5) named
#    <var>.<freq> and writes post-processed output there.  It does not
#    change the working directory; all paths are handled explicitly.

# 3. It is designed for command-file parallelism via launch_cf on
#    Casper HPC at NCAR.  It requires both NCO and CDO; when running
#    in parallel, they need to be made available via `module load`
#    commands in config_env.sh

# 4. 12-km WRF output is very large; be sure to request sufficient memory
#    (~100GB)

# 5. wbgt, utci, and humidex require the thermofeel package (ECMWF).
#    The provided nac6 conda environment includes it; create and activate
#    it from the repo with:
#      conda env create -f postprocess/environment.yml
#      conda activate nac6

# Example execution:
# ------------------------------------------------
# $ python postproc_engine.py {setupdir} {wrfout_path} 1980 tas {outdir}
# ------------------------------------------------

import thermofeel
import xarray as xr
from xarray import ufuncs
import numpy as np
import pandas as pd
import glob
import sys
import os
import time
import resource
import re
import subprocess
import warnings

t0 = time.perf_counter()

# -----------------
# keyword arguments

setupdir    = sys.argv[1]  # setup directory (contains sim.env and var_table.tsv)
wrfout_path = sys.argv[2]  # path to wrf output
year        = sys.argv[3]  # year
variable    = sys.argv[4]  # variable (cmorized syntax)
outdir      = sys.argv[5]  # output directory (variable subdirs created here)

os.makedirs(outdir, exist_ok=True)

# -------------------------------
# START OF USER DEFINED VARIABLES
# -------------------------------

# Setting to True will overwrite all post-processed data: careful!
do_overwrite_existing = True

# filename prefixes for the different types of wrfout files
wrfout_fx_fname   = "wrfout_5day_d01_"  # files that contain fixed vars
wrfout_hour_fname = "wrfout_hour_d01_"  # hourly outputs
wrfout_6hr_fname  = "wrfout_d01_"       # 6-hourly outputs
wrfout_afwa_fname = "wrfout_afwa_d01_"  # AFWA diagnostics
wrfout_pres_fname = "wrfout_pres_d01_"  # pressure-level outputs
wrfout_zlev_fname = "wrfout_zlev_d01_"  # height-AGL outputs

# -------------------------------
# END OF USER DEFINED VARIABLES
# -------------------------------


# sim.env loading
# ---------------
# Reads simulation metadata from a shell key=value file generated by setup.py.
# Values are stripped of surrounding quotes (added by setup.py for values
# containing spaces).

def load_sim_env(path):
    """Parse a shell key=value file into a dict, stripping surrounding quotes."""
    cfg = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    cfg['time_units'] = f"days since {cfg['epoch']}"
    return cfg

_cfg = load_sim_env(os.path.join(setupdir, 'sim.env'))

# fname_base components
_dom = _cfg['domain_id']              # e.g. NAM-12
_drs = _cfg['driving_source_id']      # e.g. ERA5
_dre = _cfg['driving_experiment_id']  # e.g. evaluation
_drv = _cfg['driving_variant_label']  # e.g. r1i1p1f1
_org = _cfg['institution_id']         # e.g. NCAR
_src = _cfg['source_id']              # e.g. WRF461S-SN
_ver = _cfg['version_realization']    # e.g. v1-r1

# Base filename string (without leading var and trailing freq/timespan)
# See CORDEX-CMIP6 archiving specifications for file naming conventions.
fname_base = f'{_dom}_{_drs}_{_dre}_{_drv}_{_org}_{_src}_{_ver}'


# Dimension renaming (specified by CORDEX)
dname_map_t   = {'Time': 'time'}
dname_map_xy  = {'west_east': 'x', 'south_north': 'y'}
dname_map_xyt = dname_map_t | dname_map_xy


# File naming
# -----------
def is_extensive(cell_methods):
    """Return True if cell_methods indicates an extensive variable
    (time: mean/min/max), which has time coordinates at interval midpoints."""
    return bool(re.search(r'time:\s*(mean|min|max)', cell_methods or ''))

def make_fname(var, cmor_freq, extensive=False):
    """Construct the output filename for a variable at a given frequency.
    Note extensive vars have time coordinates at midpoints of intervals.
    """
    if cmor_freq == '1hr':
        t0, t1 = ('0030', '2330') if extensive else ('0000', '2300')
        return f'{var}_{fname_base}_1hr_{year}0101{t0}-{year}1231{t1}.nc'
    elif cmor_freq == '6hr':
        t0, t1 = ('0300', '2100') if extensive else ('0000', '1800')
        return f'{var}_{fname_base}_6hr_{year}0101{t0}-{year}1231{t1}.nc'
    elif cmor_freq == 'day':
        return f'{var}_{fname_base}_day_{year}0101-{year}1231.nc'
    elif cmor_freq == 'mon':
        return f'{var}_{fname_base}_mon_{year}01-{year}12.nc'


# Time coordinate construction
# ----------------------------

# Note that although accumulated variables have an extra timestep
# going into the extract_* functions, after differencing they are the
# correct length, so they don't need a different time coordinate.

def _build_time_coord(yr, freq_hours, cell_methods):
    """Build CF-compliant time coordinate variable DataArray

    Extensive variables (cell_methods 'time: mean/min/max') have
    time_bnds and time coordinate at midpoint of the interval.
    
    Intensive variables (cell_methods 'time: point') lack time_bnds;
    time coordinate is (implicitly) at the start of the interval

    Returns (time_da, bnds_da).  bnds_da is None for intensive vars.

    """
    interval = pd.Timedelta(hours=freq_hours)

    starts = xr.date_range(
        start=f'{yr}-01-01',
        end=f'{int(yr)+1}-01-01',
        freq=f'{freq_hours}h',
        inclusive='left',
        calendar=_cfg['calendar'],
        use_cftime=True,
        unit='s',
    )

    t_encoding = {'units': _cfg['time_units'],
                  'calendar': _cfg['calendar'],
                  'dtype': np.float64
                  }

    if is_extensive(cell_methods):
        t_values = starts + interval / 2
        ends     = starts + interval
        bnds_da  = xr.DataArray(
            np.stack([starts, ends], axis=1),
            dims=['time', 'bnds'],
        )
        bnds_da.encoding = t_encoding.copy()
        bounds_attr = {'bounds': 'time_bnds'}
    else:
        t_values = starts
        bnds_da  = None
        bounds_attr = {}

    time_da = xr.DataArray(
        t_values,
        dims=['time'],
        attrs={
            'long_name':     'time',
            'standard_name': 'time',
            'axis':          'T',
            **bounds_attr,
        },
    )
    time_da.encoding = t_encoding

    return time_da, bnds_da


# File loading
# ------------
# load_wrf is called at the dispatch site using parameters from get_loader.
# The day-before file is prepended for accumulated variables so that the
# first diff gives the correct first-interval value.
#
# _day_before_file assumes Dec 31 exists in the prior year (which it
# does in standard and no-leap calendars as represented by WRF).

def _day_before_file(prefix, yr):
    """Return list containing the Dec 31 file of the prior year for prefix."""
    matches = sorted(glob.glob(f'{wrfout_path}/{prefix}{int(yr)-1}-12-31*'))
    if not matches:
        raise FileNotFoundError(
            f'Day-before file not found for year {yr} '
            f'(pattern: {wrfout_path}/{prefix}{int(yr)-1}-12-31*)')
    return matches

def load_wrf(prefix, yr, accumulated=False):
    """Load WRF output files for the given year into a dataset.

    Globs for files matching prefix+yr, sorts lexically, and prepends
    the last timestep of the day-before file when accumulated=True.
    Renames WRF dimensions to CORDEX conventions."""
    files = sorted(glob.glob(f'{wrfout_path}/{prefix}{yr}-*'))
    if not files:
        raise FileNotFoundError(
            f'No WRF files found for year {yr} '
            f'(pattern: {wrfout_path}/{prefix}{yr}-*)')

    with xr.open_dataset(files[0], decode_times=False) as _ds:
        _ny = _ds.sizes['south_north']
        _nx = _ds.sizes['west_east']
    _chunking = {'south_north': _ny, 'west_east': _nx}

    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', message='.*separate the stored chunks.*')
        ds = xr.open_mfdataset(files,
                               concat_dim='Time',
                               combine='nested',
                               chunks=_chunking,
                               mask_and_scale=False,
                               decode_times=False,
                               decode_coords=False,
                               ).fillna(1.e20)

        if accumulated:
            prev_file = _day_before_file(prefix, yr)
            prev_ds = xr.open_mfdataset(prev_file,
                                        concat_dim='Time',
                                        combine='nested',
                                        chunks=_chunking,
                                        mask_and_scale=False,
                                        decode_times=False,
                                        decode_coords=False,
                                        ).isel(Time=[-1]).fillna(1.e20)
            # NB: list index [-1] prevents loss of time dim, which
            # leads to unwanted dimension reordering on concatenation
            ds = xr.concat([prev_ds, ds], dim='Time')

    return ds.rename(dname_map_xyt)


# fx dataset: loaded from wrf.fx.nc written by setup.py.
# Contains LANDMASK, COSALPHA, SINALPHA with Time dimension already squeezed
# and dimensions renamed to CORDEX conventions (x, y).
ds_fx = xr.open_dataset(os.path.join(setupdir, 'wrf.fx.nc'))


# Output existence check
# ----------------------
def _output_needed(var, freq, fout):
    if os.path.exists(os.path.join(outdir, f'{var}.{freq}', fout)) and not do_overwrite_existing:
        print(f'{var}.{freq}/{fout} EXISTS : Skipping')
        return False
    return True


# Write extracted variables
# -------------------------
# Writes extracted data to outdir/<var>.<freq>/fname.nc.
# Attaches the time coordinate (and time_bnds for extensive variables)
# before writing.  _FillValue is set to 1e20 per CORDEX standard.
def write_vars(var_da_list, freq, time_da, bnds_da, extensive=False):
    for var, da in var_da_list:
        fout = make_fname(var, freq, extensive)
        if not _output_needed(var, freq, fout):
            continue

        vardir = os.path.join(outdir, f'{var}.{freq}')
        os.makedirs(vardir, exist_ok=True)
        outpath = os.path.join(vardir, fout)

        ds = da.assign_coords(time=time_da)
        if bnds_da is not None:
            ds = ds.assign(time_bnds=bnds_da)

        encoding = {
            var:  {'_FillValue': np.float32(1.e20)},
            'time': time_da.encoding,
        }
        if bnds_da is not None:
            encoding['time_bnds'] = bnds_da.encoding

        ds[var] = ds[var].astype(np.float32)
        ds.to_netcdf(outpath, encoding=encoding)

        
# Derive daily min/max from hourly tas
# ------------------------------------
# Called after tas has been extracted and written.  Uses cdo daymin/daymax
# on the existing tas file, then renames the variable inside.  Each runs
# only if its target output doesn't already exist (or overwrite is enabled).

def _derive_minmax(src_path, outvar, cdo_op):
    """Run cdo {cdo_op} on src_path and rename the variable to outvar."""
    out_fout = make_fname(outvar, 'day')
    out_vardir = os.path.join(outdir, f'{outvar}.day')
    out_path = os.path.join(out_vardir, out_fout)

    if not _output_needed(outvar, 'day', out_fout):
        return

    os.makedirs(out_vardir, exist_ok=True)
    subprocess.run(['cdo', '-O', cdo_op, src_path, out_path], check=True)
    roundtime = "time=round(time*2)/2;time_bnds=round(time_bnds)"
    subprocess.run(['ncap2', '-h', '-O', '-s', roundtime, out_path, out_path], check=True)
    subprocess.run(['ncrename', '-h', '-v', f'tas,{outvar}', out_path], check=True)

def derive_tasmin(tas_path):
    _derive_minmax(tas_path, 'tasmin', 'daymin')

def derive_tasmax(tas_path):
    _derive_minmax(tas_path, 'tasmax', 'daymax')


# Import extract functions
# ------------------------
# All shared state above is now defined; importing variables.py here allows
# its functions to close over names in this module's global namespace.
_variables_path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                               'postproc_vars.py')
with open(_variables_path) as _f:
    exec(compile(_f.read(), _variables_path, 'exec'), globals())


# Dispatch tables
# ---------------

# maps CMOR frequency strings to hours (for _build_time_coord).
_FREQ_HOURS = {'1hr': 1, '6hr': 6, 'day': 24}

# Variables whose WRF fields are accumulated totals requiring
# differencing; the day-before file is prepended before loading.
_ACCUMULATED = {'pr', 'rsds', 'rlds', 'mrro', 'mrros', 'snm', 'fzra'}

# Which kind of file to find the variables in.  Variables not
# listed here default to wrfout_hour_fname (non-accumulated).
_FILE_VARS = {
    wrfout_afwa_fname: {'psl', 'cape', 'cin', 'prw', 'fzra', 'heatidx', 'wchill'},
    wrfout_6hr_fname:  {'snw', 'snd', 'mrso', 'mrros', 'mrro',
                        'rsus', 'rlus', 'hfls', 'hfss', 'snm'},
    wrfout_pres_fname: {'ua700', 'ua500', 'ua250',
                        'va700', 'va500', 'va250',
                        'ta700', 'ta500', 'ta250',
                        'zg700', 'zg500', 'zg250',
                        'hus700', 'hus500', 'hus250'},
    wrfout_zlev_fname: {'ua50m', 'ua100m', 'ua150m',
                        'va50m', 'va100m', 'va150m'},
}

# Invert _FILE_VARS: var -> prefix (default: wrfout_hour_fname)
_VAR_PREFIX = {var: prefix
               for prefix, varset in _FILE_VARS.items()
               for var in varset}

# Frequency of each wrfout file type.
_PREFIX_FREQ = {
    wrfout_hour_fname: '1hr',
    wrfout_afwa_fname: '1hr',
    wrfout_6hr_fname:  '6hr',
    wrfout_pres_fname: '6hr',
    wrfout_zlev_fname: '6hr',
}

# Variables derived from tas via cdo after extraction, rather than being
# extracted directly.  Requesting them as standalone jobs is an error;
# run tas instead.
_DERIVED_FROM_TAS = {'tasmin', 'tasmax'}

# wbgt and utci both resolve to extract_wbgt_utci, which loads its own
# files one day at a time and writes output directly (returning an empty
# list).  They are called without ds arguments.  Submitting
# utci as a standalone job would conflict with wbgt output; use --vars wbgt
# to get both.
_SELF_LOADING = {'wbgt', 'utci'}

# Load var_table; index by 'var' column for fast lookup
_var_table = pd.read_csv(os.path.join(setupdir, 'var_table.tsv'), sep='\t',
                         index_col='var')

# All non-fx variables we expect to produce (var_table excludes fx rows)
_ALL_VARS = set(_var_table.index)


def get_extract_fn(var):
    """Return the extract function for var, or None if not found."""
    if var in _SELF_LOADING:
        return extract_wbgt_utci
    return globals().get(f'extract_{var}')

def get_loader(var):
    """Return (prefix, freq_hours, accumulated) for var."""
    prefix      = _VAR_PREFIX.get(var, wrfout_hour_fname)
    freq_hours  = _FREQ_HOURS[_PREFIX_FREQ[prefix]]
    accumulated = var in _ACCUMULATED
    return prefix, freq_hours, accumulated


# Call functions
# --------------
if variable in _DERIVED_FROM_TAS:
    print(f'{variable} is derived from tas; run tas instead.')
    sys.exit(0)

if variable not in _ALL_VARS:
    print(f'Error: {variable} not found in var_table')
else:
    extract_fn = get_extract_fn(variable)
    if extract_fn is None:
        print(f'Warning: no extract function found for {variable}')
    else:
        prefix    = _VAR_PREFIX.get(variable, wrfout_hour_fname)
        freq      = _PREFIX_FREQ[prefix]
        cm  = _var_table.loc[variable, 'cell_methods'] if variable not in _SELF_LOADING else None
        ext = is_extensive(cm)
        if _output_needed(variable, freq, make_fname(variable, freq, ext)):
            if variable in _SELF_LOADING:
                write_vars(extract_fn(), freq, None, None)
            else:
                _, freq_hours, accumulated = get_loader(variable)
                ds       = load_wrf(prefix, year, accumulated)
                time_da, bnds_da = _build_time_coord(year, freq_hours, cm)
                write_vars(extract_fn(ds), freq, time_da, bnds_da, ext)
                ds.close()

        # Derive tasmin/tasmax from the tas file.  Runs whether or not
        # tas was just regenerated (each derive does its own existence
        # check), so missing tasmin/tasmax can be filled in without
        # forcing tas to be rebuilt.
        if variable == 'tas':
            tas_path = os.path.join(outdir, 'tas.1hr',
                                    make_fname('tas', '1hr', ext))
            derive_tasmin(tas_path)
            derive_tasmax(tas_path)

print(f'postproc time: {time.perf_counter() - t0:.1f} sec')
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f'postproc max memory: {mem / (1024*1024):.1f} GB')
