# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis

# Purpose:
# --------
# Extract WBGT and UTCI from a month's worth of WRF hourly output files
# (one file per day). Both indices are computed together since they share
# the expensive MRT calculation.
#
# Parallelized at the month level (rather than per-day) to keep total task
# counts manageable for large simulations; each invocation loops over the
# days in one year-month and still writes one output file per day, so
# downstream concatenation (wbgt_cat.cmd in extract.sh) is unchanged.
#
# USAGE:
#   python postproc_wbgt.py SETUPDIR CHUNKDIR YEAR MONTH OUTDIR
#
#   SETUPDIR  Directory containing sim.env (produced by setup.py)
#   CHUNKDIR  Directory containing WRF hourly files for this chunk
#   YEAR      4-digit year (e.g. 1980)
#   MONTH     2-digit month (e.g. 01)
#   OUTDIR    Output directory (wbgt.1hr/ and utci.1hr/ created here)
#
# Output files (one pair per day in the month):
#   OUTDIR/wbgt.1hr/YEAR/wbgt_{fname_base}_1hr_{YYYYMMDD}0000-{YYYYMMDD}2300.nc
#   OUTDIR/utci.1hr/YEAR/utci_{fname_base}_1hr_{YYYYMMDD}0000-{YYYYMMDD}2300.nc
#
# References:
#   MRT: Di Napoli et al. (2020), Int J Biometeorol, 64:1233-1245
#   Globe T: Guo et al. (2018), Energy and Buildings
#   Wet bulb T: Stull (2011), J Appl Meteorol Climatol, 50:2267-2269
#   WBGT: ISO 7243 (2017); WBGT = 0.7*Tw + 0.2*Tg + 0.1*Ta
#   thermofeel: Brimicombe et al. (2022), SoftwareX, 18, 101005

import thermofeel
import xarray as xr
import numpy as np
import pandas as pd
import sys
import os
import re
import glob
import time
import resource

t0 = time.perf_counter()

# -----------------
# Arguments

setupdir = sys.argv[1]
chunkdir = sys.argv[2]
year     = sys.argv[3]
month    = sys.argv[4]
outdir   = sys.argv[5]

os.makedirs(outdir, exist_ok=True)

infiles = sorted(glob.glob(os.path.join(chunkdir, f'wrfout_hour_d01_{year}-{month}-*')))
if not infiles:
    print(f'Error: no files found for {year}-{month} in {chunkdir}', file=sys.stderr)
    sys.exit(1)

# -----------------
# sim.env loading
# Reads simulation metadata from a shell key=value file generated by setup.py.
# Values are stripped of surrounding quotes (added by setup.py for values
# containing spaces).

def load_sim_env(path):
    """Parse a shell key=value file into a dict, stripping surrounding quotes."""
    cfg = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    cfg['time_units'] = f"days since {cfg['epoch']}"
    return cfg

_cfg = load_sim_env(os.path.join(setupdir, 'sim.env'))

_dom = _cfg['domain_id']
_drs = _cfg['driving_source_id']
_dre = _cfg['driving_experiment_id']
_drv = _cfg['driving_variant_label']
_org = _cfg['institution_id']
_src = _cfg['source_id']
_ver = _cfg['version_realization']

fname_base = f'{_dom}_{_drs}_{_dre}_{_drv}_{_org}_{_src}_{_ver}'

_t_encoding = {
    'units':    _cfg['time_units'],
    'calendar': _cfg['calendar'],
    'dtype':    np.float64,
}

# -----------------
# Output directories (same for every day in this year-month)

os.makedirs(os.path.join(outdir, 'wbgt.1hr', year), exist_ok=True)
os.makedirs(os.path.join(outdir, 'utci.1hr', year), exist_ok=True)

# -----------------
# WRF variables needed

_WBGT_WRF_VARS = ['T2', 'Q2', 'PSFC', 'U10', 'V10', 'COSZEN',
                   'SWDOWN', 'SWDDNI', 'GLW', 'LWUPB', 'ALBEDO']

# -----------------
# Physics helpers

def _vapor_pressure_from_q(q, P):
    """Vapor pressure (Pa) from mixing ratio (kg/kg) and pressure (Pa)."""
    hus = q / (1 + q)    # mixing ratio -> specific humidity
    eps = 0.62197
    return hus * P / (eps + hus * (1.0 - eps))


def _compute_wbgt_utci_arrays(ds):
    """Compute WBGT and UTCI from a single-day WRF dataset.

    Returns (wbgt, utci) as float32 arrays shaped (time, y, x).
    MRT is computed once and shared between both indices.
    """
    COSZEN = np.clip(ds['COSZEN'].values, 0.0, 1.0)
    SWDOWN = np.maximum(np.nan_to_num(ds['SWDOWN'].values, nan=0.0), 0.0)
    SWDDNI = np.maximum(np.nan_to_num(ds['SWDDNI'].values, nan=0.0), 0.0)
    GLW    = np.maximum(np.nan_to_num(ds['GLW'].values,    nan=0.0), 0.0)
    LWUPB  = np.maximum(np.nan_to_num(ds['LWUPB'].values,  nan=0.0), 0.0)
    ALBEDO = np.nan_to_num(ds['ALBEDO'].values, nan=0.2)
    T2   = ds['T2'].values
    Q2   = np.maximum(ds['Q2'].values, 0.0)
    PSFC = ds['PSFC'].values
    U10  = ds['U10'].values
    V10  = ds['V10'].values

    ssrd = SWDOWN
    ssr  = SWDOWN * (1.0 - ALBEDO)
    dsrp = SWDDNI
    strd = GLW
    fdir = np.minimum(SWDDNI * COSZEN, SWDOWN)
    strr = GLW - LWUPB

    mrt = thermofeel.calculate_mean_radiant_temperature(
        ssrd=ssrd, ssr=ssr, dsrp=dsrp,
        strd=strd, fdir=fdir, strr=strr,
        cossza=COSZEN,
    )

    wspd  = np.maximum(np.sqrt(U10**2 + V10**2), 0.5)
    e_a   = _vapor_pressure_from_q(Q2, PSFC)
    e_hPa = np.maximum(e_a / 100.0, 0.001)
    ln_e  = np.log(e_hPa / 6.1078)
    tdew  = (237.3 * ln_e) / (17.27 - ln_e) + 273.15   # dew point (K)

    wbgt = thermofeel.calculate_wbgt(t2_k=T2, mrt=mrt, va=wspd, td_k=tdew)
    utci = thermofeel.calculate_utci(t2_k=T2, va=wspd, mrt=mrt, td_k=tdew)

    # Mask UTCI outside the valid input range of the thermofeel polynomial
    ta_c  = T2 - 273.15
    mrt_c = mrt - 273.15
    valid = (
        (ta_c  >= -50) & (ta_c  <= 50) &
        (wspd  <= 17) &
        ((mrt_c - ta_c) >= -30) & ((mrt_c - ta_c) <= 70)
    )
    utci = np.where(valid, utci, np.nan)

    return wbgt.astype(np.float32), utci.astype(np.float32)


# -----------------
# Chunking, based on domain size (same for every file in this chunk)

with xr.open_dataset(infiles[0], decode_times=False) as _ds0:
    _ny = _ds0.sizes['south_north']
    _nx = _ds0.sizes['west_east']
_chunking = {'south_north': _ny, 'west_east': _nx}

# -----------------
# Process a single day's file: parse day, load, compute, write.
# Daily files are staged in <outdir>/<var>.1hr/<year>/ so that the
# per-year ncrcat commands in wbgt_cat.cmd can glob cleanly by year.

def process_day(infile):
    # Day comes from the filename; year/month are fixed for this job.
    # Expected filename format: wrfout_hour_d01_YYYY-MM-DD_HH:MM:SS
    _fname = os.path.basename(infile)
    _m = re.search(r'\d{4}-\d{2}-(\d{2})', _fname)
    if not _m:
        print(f'Error: could not parse date from filename: {_fname}', file=sys.stderr)
        sys.exit(1)
    day = _m.group(1)
    date_str = f'{year}{month}{day}'   # YYYYMMDD, used in output filenames

    # Time coordinate. WBGT/UTCI are instantaneous, so no time_bnds.
    time_da = xr.DataArray(
        xr.date_range(
            start=f'{year}-{month}-{day}',
            periods=24,
            freq='1h',
            calendar=_cfg['calendar'],
            use_cftime=True,
            unit='s',
        ),
        dims=['time'],
        attrs={
            'long_name':     'time',
            'standard_name': 'time',
            'axis':          'T',
        },
    )
    time_da.encoding = _t_encoding

    wbgt_fout = os.path.join(
        outdir, 'wbgt.1hr', year,
        f'wbgt_{fname_base}_1hr_{date_str}0000-{date_str}2300.nc')
    utci_fout = os.path.join(
        outdir, 'utci.1hr', year,
        f'utci_{fname_base}_1hr_{date_str}0000-{date_str}2300.nc')

    ds = xr.open_dataset(infile, engine='netcdf4',
                         chunks=_chunking,
                         mask_and_scale=False,
                         decode_times=False,
                         decode_coords=False)[_WBGT_WRF_VARS]
    ds = ds.rename({'Time': 'time', 'west_east': 'x', 'south_north': 'y'})

    wbgt_arr, utci_arr = _compute_wbgt_utci_arrays(ds)
    ds.close()

    _encoding_base = {
        'time': _t_encoding,
    }

    xr.DataArray(wbgt_arr, dims=['time', 'y', 'x'], coords={'time': time_da}) \
      .to_dataset(name='wbgt') \
      .to_netcdf(wbgt_fout,
                 encoding={'wbgt': {'_FillValue': np.float32(1.e20)},
                           **_encoding_base},
                 unlimited_dims=['time'])

    xr.DataArray(utci_arr, dims=['time', 'y', 'x'], coords={'time': time_da}) \
      .to_dataset(name='utci') \
      .to_netcdf(utci_fout,
                 encoding={'utci': {'_FillValue': np.float32(1.e20)},
                           **_encoding_base},
                 unlimited_dims=['time'])

    print(f'  wbgt/utci: {date_str} finished')


# -----------------
# Process each day in the month

for _infile in infiles:
    process_day(_infile)

print(f'postproc time: {time.perf_counter() - t0:.1f} sec')
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f'postproc max memory: {mem / (1024*1024):.1f} GB')
