# Authors: Jacob Stuivenvolt-Allen, Seth McGinnis

# Purpose:
# --------
# This script extracts the time-invariant (fx) variables orog and sftlf
# from a WRF input file.  It is a standalone script that does not depend
# on postprocess.machinery.py.
#
# Unlike the time-varying variables, fx variables come from a WRF *input*
# file (wrfinput_d01) rather than an output file, using the path recorded
# in sim.env.

# USAGE NOTES:
# -----

# 1. This script extracts orog and sftlf; it takes no variable argument.

# argument 1 : Setup directory (contains sim.env, generated by setup.py)
# argument 2 : Output directory (where variable subdirs are created)

# Example execution:
# ------------------------------------------------
# $ python postprocess.fx.py {setupdir} {outdir}
# ------------------------------------------------

import xarray as xr
import numpy as np
import sys
import os
import time
import resource

t0 = time.perf_counter()

setupdir = sys.argv[1]
outdir   = sys.argv[2]

os.makedirs(outdir, exist_ok=True)


# sim.env loading
# ---------------
def load_sim_env(path):
    """Parse a shell key=value file into a dict, stripping surrounding quotes."""
    cfg = {}
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' not in line:
                continue
            k, _, v = line.partition('=')
            cfg[k.strip()] = v.strip().strip('"').strip("'")
    return cfg

_cfg = load_sim_env(os.path.join(setupdir, 'sim.env'))

wrfinput_path = _cfg['wrfinput_path']

_dom = _cfg['domain_id']
_drs = _cfg['driving_source_id']
_dre = _cfg['driving_experiment_id']
_drv = _cfg['driving_variant_label']
_org = _cfg['institution_id']
_src = _cfg['source_id']
_ver = _cfg['version_realization']

fname_base = f'{_dom}_{_drs}_{_dre}_{_drv}_{_org}_{_src}_{_ver}'

dname_map_xy = {'west_east': 'x', 'south_north': 'y'}


# Time invariant variables (orog and sftlf)
# ---------------------------------------------------
# orog & sftlf must be produced from a WRF *input* file rather than an output
# file; note they have no time dimension.
#
# sftlf is the land fraction excluding sea ice (LANDMASK - SEAICE).
# orog is the surface altitude (HGT).

infile = os.path.join(wrfinput_path, 'wrfinput_d01')
ds = xr.open_dataset(infile, decode_times=False) \
       .rename(dname_map_xy) \
       .fillna(1.e20)

seaice = ds['SEAICE'].mean(dim='Time')
sftlf  = (ds['LANDMASK'].mean(dim='Time') - xr.where(seaice != 0, 1, 0)) * 100
orog   = ds['HGT'].mean(dim='Time')

for varname, da in [('sftlf', sftlf), ('orog', orog)]:
    fout = f'{varname}_{fname_base}_fx.nc'
    vardir = os.path.join(outdir, varname)

    if os.path.exists(os.path.join(vardir, fout)):
        print(f'fx: {varname} already exists, skipping')
        continue

    os.makedirs(vardir, exist_ok=True)
    da.to_dataset(name=varname).drop_attrs() \
      .astype(np.float32) \
      .to_netcdf(os.path.join(vardir, fout))

print(f'postproc time: {time.perf_counter() - t0:.1f} sec')
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
print(f'postproc max memory: {mem / (1024*1024):.1f} GB')
